### ISSUE TITLE
Installing executables with ‘go get’ in module mode is deprecated in Go 1.7

### ISSUE THREAD

**Issue by aarrtteemm** [google/der-ascii#20]
Documentation for the tool suggests the usage of `go get` for installing the command. However, this command is deprecated in Go 1.7. It takes some time for ones who are not experienced with Go eco-system to install the tool. I personally came up with the solution below but I'm sure there is a more Go-ish way to do it. Please update the documentation with the corresponding command(s).

```
git clone https://github.com/google/der-ascii.git
cd der-ascii
go install ./cmd/...
```

**Comment by thgoebel** [comment]
`go install github.com/google/der-ascii/cmd/...@latest` worked for me ([docs](https://go.dev/doc/go-get-install-deprecation)).

**Comment by davidben** [comment]
Oops, somehow I missed this bug report. Thanks @thgoebel for providing a fix!
