### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by hawkw** [google/der-ascii#23]
Hi, I'd like to package `der2ascii` and `ascii2der` for my package manager of choice. However, this package manager requires some kind of versioning scheme. Would it be possible to introduce some form of versioning, such as Git tags for releases? 

Thank you for writing such a useful tool!

**Comment by cpu** [comment]
Chiming in to say I would also find this helpful. I've been packaging this tool for my own projects pinning to HEAD and it prevents upstreaming the package definition for others to benefit from.

**Comment by davidben** [comment]
What would you want the versions to mean? I don't want to spend any time managing releases and especially not semver expectations, so likely I would just stamp a 0.x version every time I make a commit and not think about this very hard.

**Comment by hawkw** [comment]
Ideally, I would like backwards-incompatible changes to the CLI and textual syntax (e.g. removing a CLI flag, or removing/renaming a syntactic construct) to be considered an incompatible version. I understand that this is extra work for the authors, but it would be nice for downstream users to be able to, for example, use `ascii2der` in a script and rely on the command-line interface not breaking.

If that's not something you're willing to do, I understand, and a versioning scheme where you increment a counter whenever you want to is also fine...at the end of the day, I just need *something* I can use to populate the "version" field in a package definition. :)

**Comment by cpu** [comment]
>  I don't want to spend any time managing releases and especially not semver expectations

That's reasonable, but it does feel like [the README's existing backwards compatibility section](https://github.com/google/der-ascii#backwards-compatibility) advertises something approaching semver expectations.

> so likely I would just stamp a 0.x version every time I make a commit and not think about this very hard.

+1-ing that I think this would be helpful. From the perspective of a downstream user it's easier to notice new tags being published than it is to catch new commits arriving on the convergence branch when pull requests aren't being used. I believe GitHub produces notifications for repo watchers for new tags, but it doesn't for new commits on `main`.

**Comment by davidben** [comment]
README contains vague compat goals, but that is not a formal semver promise, no. Obviously trying to avoid breaking things is good, but, e.g., c8bb0d34a6e5137706f4e5924073f3a1066b902f fixed a bug and was not strictly speaking backwards-compatible. Yet I doubt anyone's use will be actually impacted. I'm sure that won't be the last mistake I make.

Conversely, even though the README disclaims that `der2ascii`'s output is unstable (necessarily so as it's just a heuristic), I'm sure people will write scripts that rely on this. Treating those as breaking means every change is a breaking change.

And, of course, unspoken in the usual semver expectations is that, when a major bump happens the authors will maintain both branches for a long period of time and then communicate a length end-of-life process. I don't have that one I'm afraid.

Semver is ultimately a very poor approximation of managing a breakage budget, which tends to lead to busywork and unhappiness on all sides.

**Comment by hawkw** [comment]
For the record, I'm certainly not approaching this with the expectation of long-term support for older versions after a breaking change.

**Comment by cpu** [comment]
I'm happy to have tags to point to and use to discover new changes in the codebase. Strict semver adherence not required :) If every tag was a major version bump, and happened for ~every commit, I wouldn't complain.

**Comment by davidben** [comment]
Alright, well, I've made a `v0.1.0`. Not like this thing actually changes much anyway. :-)
